version: '3'
services:
  mongodb: 
    image: mongo
    restart: always
    container_name: mongodb
    ports: 
      - 27017:27017
    volumes:
      - ./DSPharmacy/data:/data/db
  dspharmacy:
    build: .
    restart: always
    container_name: DSPharmacy
    depends_on:
      - mongodb 
    ports:
      - 5000:5000
    environment:
      - MONGO_HOST=mongodb
